### ISSUE TITLE
create_dataset.py script is very slow

### ISSUE THREAD

**Issue by helboukkouri** [SotirisKot/Content-Aware-N2V#2]
Hi :) I am having an issue reproducing the results from your paper.
So I run the following command to build the 'is_a' dataset:

`python create_dataset.py --input datasets/relation_instances_edgelists/isa.edgelist --dataset isa`

But the script seems to be very slow (> 1 day just to build the positive test samples):

<img width="935" alt="Screenshot 2019-10-16 at 15 31 05" src="https://user-images.githubusercontent.com/36409068/66893898-11d56080-f02a-11e9-822c-9c46d9a76b24.png">

Is this normal ? @SotirisKot

**Comment by SotirisKot** [comment]
Hello!
Yes, this is normal. Everytime you remove an edge (as a positive test
sample) you have to check if the network remains connected. This takes
time.
When we remove a positive edge e.g. (i, j) , we run bfs to check if j is
still reachable from i.
This overhead applies only to generating positive test samples.
Feel free to suggest any ideas for improving the speed :)

Best Regards,
Sotiris

Στις Τετ, 16 Οκτ 2019 στις 9:34 π.μ., ο/η Hicham EL BOUKKOURI <
notifications@github.com> έγραψε:

**Comment by helboukkouri** [comment]
Thank you for your quick answer. :)

**Comment by akastrin** [comment]
To speed up the procedure you could apply loop erasing random walk algorithm instead of BFS approach.
