### ISSUE TITLE
How to compute network embeddings properly?

### ISSUE THREAD

**Issue by akastrin** [SotirisKot/Content-Aware-N2V#3]
Hi,

I try to understand the procedure around the link prediction using the network embeddings. You stated in the paper:
> Node embeddings are obtained by applying a NE method to the pruned network, i.e., after removing the true positives.

If I understand your paper correctly, I need to compute embeddings on the "train negative" set only? But how are then properties of the network preserved?

Thanks, Andrej

**Comment by SotirisKot** [comment]
Hello, sorry for the delayed response.

You remove from the network a number of true positives (with the costraint that the network must remain connected). The removed true positives can be used for dev set and test set. 

The remaining true positives will constitute your train graph. This is where you will learn your node embeddings. 

I hope that helps,
Sotiris

**Comment by akastrin** [comment]
Thanks for your answer.

Best, Andrej
